apiVersion: v1
kind: Service
metadata:
  name: student-registry-service
spec:
  type: NodePort
  selector:
    app: student-registry
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
